export enum AppEventType {
  DEFAULT_EVENT = 'DEFAULT_EVENT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE = 'LOGOUT_FAILURE',
  SESSION_VALID = 'SESSION_VALID',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
}
